services:
    app.user_locale_listener:
        class: PlatformBundle\EventListener\UserLocaleListener
        arguments: ["@session", "%kernel.default_locale%", "%locale_supported%"]
        tags:
            - { name: kernel.event_subscriber }

    platform.view.exception_wrapper_handler:
        class: PlatformBundle\View\ExceptionWrapperHandler
        arguments:
            logger: "@?logger"

    platform.logout_success_handler:
        class: PlatformBundle\Security\LogoutSuccessHandler
        arguments: ["@security.context", "@doctrine.orm.default_entity_manager"]

    amazon_s3_client:
        class: Aws\S3\S3Client
        factory_class: Aws\S3\S3Client
        factory_method: factory
        arguments:
            -
              region: %amazon_s3_region%
              version: %amazon_s3_version%
              credentials:
                  key: %amazon_s3_key%
                  secret: %amazon_s3_secret%

    platform.amazon_s3_service:
        class: PlatformBundle\Services\AmazonS3
        arguments:
          - @amazon_s3_client

    platform.generate_thumbnail_consumer:
        class: PlatformBundle\Consumer\GenerateThumbnailConsumer
        arguments:
          - @logger
          - @doctrine.orm.default_entity_manager
          - @liip_imagine.data.manager
          - @liip_imagine.filter.manager
          - @platform.amazon_s3_service
          - %kernel.root_dir%