parameters:
    database_host:        127.0.0.1
    database_port:        5432
    database_name:        null
    database_user:        null
    database_password:    null
    mailer_transport:     smtp
    mailer_host:          127.0.0.1
    mailer_user:          null
    mailer_password:      null
    secret:               null
    elastica_host:        127.0.0.1
    elastica_port:        9200
    elastica_url:         null
    rabbitmq_host:        127.0.0.1
    rabbitmq_port:        5672
    rabbitmq_user:        null
    rabbitmq_password:    null
    rabbitmq_vhost:       /
    amazon_s3_key:        null
    amazon_s3_secret:     null
    amazon_s3_region:     eu-west-1
    amazon_s3_version:    latest